[[COINGECKO_ID_EXPLICIT]]
aave = "aave"
ada = "cardano"
abccvx-gauge = "convex-finance"
abccvx = "convex-finance"
acrv = "aladdin-cvxcrv"
afrxeth = "frax-ether"
avax = "avalanche-2"
b-90clevcvx-10cvx = "convex-finance"
bch = "bitcoin-cash"
bifi = "beefy-finance"
bnb = "binancecoin"
boo = "spookyswap"
bshare = "based-shares"
clevcvx = "clever-cvx"
cnc = "conic-finance"
ctr = "concentrator"
cvxfxs = "convex-fxs"
cvxfxsfxs-f = "convex-fxs"
dot = "polkadot"
eth = "ethereum"
frxethcrv = "curve-dao-token"
ftm = "fantom"
geth = "geist-eth"
gftm = "geist-ftm"
gmx = "gmx"
grt = "the-graph"
ice = "ice-token"
ldo = "lido-dao"
link = "chainlink"
lusd = "liquity-usd"
memo = "wonderland"
mim = "magic-internet-money"
mootombtomb-ftm = "fantom"
pxcvx = "convex-finance"
sd = "stader"
sdog = "snowdog"
sdt = "stake-dao"
shib = "shiba-inu"
spa = "spartacus"
spirit-lp = "spiritswap"
splp = "splp"
sspa = "spartacus"
sspell = "spell-token"
stkcvxcrv = "convex-crv"
time = "wonderland"
tomb-v2-lp = "tomb"
ucrv = "curve-dao-token"
ucvx = "convex-finance"
ucvxcrv = "convex-crv"
usdc = "usd-coin"
weth = "ethereum"
xald = "aladdin-dao"
