DEBANK_ALLOW_LIST = [
    "9b9854c53b5aca16cdbf5f25f9245ea5",           # veDEUS
    "0x10720a029a5e5281391be3181477e48d47d0ff91", # SDOG
    "0x8e2549225e21b1da105563d419d5689b80343e01", # sSPA
]

DEBANK_SPAM_TOKEN_IDS = [
    "0x2dbed4d7a843796c6e985db5368f2bbcaa785cda", # PEPE (FAKE VERSION)
    "0x5b942470df39cfcad4348585fb5507d4c333a91f", # BALD (FAKE VERSION)
]

DEBANK_SPAM_TOKEN_NAMES = [
    "(BNB)",
    "# Visit UrgentDT.com to secure your funds ASAP. A hacker has access to your funds.",
    "$ ConvexLR.com  - Visit to claim bonus rewards",
    "$ Free Claim and Play",
    "$ UniswapLR.com @ 5.75",
    "$ USDCDrop.com <- Visit to claim",
    "$ wBTCLP.com - Visit to claim bonus rewards",
    "1BNB",
    "1XBET",
    "Access token to https://dydxfi.org",
    "AIINEDIBLE",
    "AMC",
    "ARBK",
    "arbSwap.club",
    "AvaxClassic.com",
    "AWDD",
    "BABYRFD",
    "BaseX",
    "BlurAirdropBox",
    "BTCETH",
    "Claim USDC at https://chaingeusdc.top",
    "Claim USDC at https://cusdc.disusd.eth.limo",
    "CocoX",
    "CONNECT",
    "CYBER",
    "CyberX",
    "DEV",
    "DogeX",
    "EGOD",
    "FIGHT",
    "FK12",
    "Incubator",
    "kUSDC.org",
    "LIL",
    "LOOKSDROP.COM",
    "LPUniV3.com",
    "M32",
    "MEME",
    "MEV",
    "moaAVXMVT",
    "mScDAIMVT",
    "mScWETHMVT",
    "NHTYWEW",
    "Nobody",
    "Noox Distribution Protocol",
    "NOTIONAL_BETA",
    "NUDES",
    "PGold",
    "PHY",
    "PNDC",
    "PPND",
    "RABBY",
    "REKT",
    "Reward Token - Claim at https://stUSD.tech",
    "Rewards Token From https://avpool.site",
    "ROLEX",
    "RPL: Rewards Pass",
    "Socks powered by Unisocks.Fi",
    "SpaceX",
    "Swap at LINKToken.io",
    "TANK",
    "TIA",
    "TOMI",
    "TRON",
    "Unisocks",
    "UniswapLP.com",
    "Uniswapv3LP.com",
    "USDCGOLD.COM",
    "Visit https://aeth.trade to claim rewards",
    "Visit https://apyeth.net to claim rewards",
    "Visit https://arbinu.fun to claim rewards.",
    "Visit https://axdom.site to claim rewards.",
    "Visit https://convex.bz to claim rewards.",
    "Visit https://creth.xyz to claim rewards.",
    "Visit https://ethapy.org to claim rewards",
    "Visit https://gpepe.org to claim rewards.",
    "Visit https://gpepe.xyz to claim rewards.",
    "Visit https://incr.fi and claim genesis airdrops.",
    "Visit https://mpepe.xyz to claim rewards.",
    "Visit https://obonus.site to claim reward",
    "Visit https://usd2023.com to claim rewards",
    "Visit https://usdreward.com to claim rewards",
    "WAVAX.net",
    "WETH Powered By Noox.fi",
    "WETH Powered By Noox.Fi",
    "WETH Powered By Noox.tech",
    "wHEX",
    "X2.0",
    "X3.0",
    "YES2049",
    "YUGA x GUCCI Merch",
    "ZachXBT.xyz",
    "ZPR NFT",
    "ZRO",
    "ZT.WTF",
]
