STABLECOINS = [
    "alusd",
    "bpt-deiusdc",
    "bpt-guqinqi",
    "bpt-mimusdcust",
    "busd",
    "cad",
    "clevusd",
    "clevusd3crv-f",
    "crvusd",
    "crvusdusdc-f",
    "dai.e",
    "dai",
    "frax",
    "fraxbp-f",
    "fusdt",
    "gdai",
    "gusd",
    "hmim",
    "lusd",
    "lusd3crv-f",
    "mai",
    "mim",
    "mimatic",
    "moobeetdoubledollarfugue",
    "moobeetguqinqi2",
    "moogeistmim",
    "mooscreamdai",
    "s*usdc",
    "usd",
    "usdc.e",
    "usdc",
    "usde",
    "usdt.e",
    "usdt",
    "ust",
]
