# The following transaction names are considered to be income.
income_txns = [
    'claim',
    'claim_rewards',
    'claimAll',
    'claimAllCTR',
    'claimFromDistributorViaUniV2EthPair',
    'claimMulti',
    'claimReward',
    'claimRewards',
    'getReward',
    'harvest',
    'redeem',
    'Interest',
    'Interest Payment',
    'Rewards Income'
]

[reports]

# The files listed below should be replaced with your actual path and filename.
# If it is not found, you will see a WARN at the command line but it will
# continue to execute.

[reports.manual-1]
file = "data/reports/manual.csv"
parser = "default"

[reports.coinbase-1]
file = "data/reports/2015-2021-coinbase/Coinbase-2021-CB-RAWTX_.csv"
parser = "coinbase_us"

[reports.coinbase-2]
file = "data/reports/2022-coinbase/Coinbase-54bf32440c6950491100003f-TransactionsHistoryReport-2023-10-10-09-32-59.csv"
parser = "coinbase_us_2022"

[reports.coinbase-3]
file = "data/reports/2023-coinbase/b2cc0a0e-74da-5fec-9c59-87c675c788cc_transactions_history.csv"
parser = "coinbase_us_2023"

[reports.coinbase-pro-1]
file = "data/reports/2022-coinbasepro/account.csv"
parser = "coinbasepro_us"

[reports.binance-1]
file = "data/reports/2021-binance/202212041409.csv"
parser = "binance_us"

[reports.binance-2]
file = "data/reports/2022-binance/202212131739.csv"
parser = "binance_us"

[reports.blockfi-1]
file = "data/reports/all-blockfi/trade_report_all.csv"
parser = "blockfi"

[reports.kucoin-1]
file = "data/reports/2021-10-01-2022-10-01-kucoin/Spot Orders_Historical Orders20230113.csv"
parser = "kucoin_us"


[output]
show_tags = true


[consolidated_parser]

# Equivalent pairs must be alphabetical
equivalents = [
    # ["abccvx", "abccvx-gauge"],
    # ["b-90clevcvx-10cvx", "b-90clevcvx-10cvx-gauge"],
    # ["b-98acrv-2ctr", "b-98acrv-2ctr-gauge"],
    # ["blusdlusd3-f", "blusdlusd3-f-gauge"],
    # ["bpt-beets-ftm", "fbeets"],
    # ["clevcvx-f", "clevcvx-f-gauge"],
    # ["clevcvx", "clevcvx-f"],
    # ["cleveth-f", "cleveth-f-gauge"],
    # ["clevusd", "clevusd3crv-f"],
    # ["cmumami", "mumami"],
    # ["crv", "sdcrv-gauge"],
    # ["crvusdusdc-f", "crvusdusdc-f-gauge"],
    # ["ctreth-f", "ctreth-f-gauge"],
    # ["cvxfraxbp-f", "fraxbp-f"],
    # ["eth", "geth"],
    ["eth", "leth"],
    # ["eth", "steth"],
    ["eth", "weth"],
    # ["fmootombtomb-ftm-3", "mootombtomb-ftm"],
    # ["fmootombtomb-ftm", "mootombtomb-ftm"],
    ["ftm", "wftm"],
    # ["gmx", "sbfgmx"],
    # ["hmim", "hmim-gauge"],
    # ["jxjoe", "xjoe"],
    # ["matic", "wmatic"],
    # ["memo", "time"],
    # ["mumami", "umami"],
    # ["pxcvx", "ucvx"],
    # ["sdCRV", "sdCRV-gauge"],
    # ["sdog", "ssdog"],
    # ["spa", "sspa"],
    # ["tbond", "tomb"],
]

[token_name_overrides]
"0xcbf6f78981e63ef813cb71852d72a060b583eecf" = "SLP MATIC-FISH"
"0xa79983daf2a92c2c902cd74217efe3d8af9fba2a" = "SLP TITAN-MATIC"
"0x85de135ff062df790a5f20b79120f17d3da63b2d" = "SLP IRON-USDC"
